version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080